# docker-compose.yml

services:
  monarc:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - MONARC_VERSION=v2.13.3-p2
      - DB_USER=monarc
      - DB_PASSWORD=anothers3cret!
      - DB_ROOT_PASSWORD=tops3cret§
    volumes:
      - monarc_data:/var/lib/monarc/fo-data

  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=tops3cret§
      - MYSQL_DATABASE=monarc_cli
      - MYSQL_USER=monarc
      - MYSQL_PASSWORD=anothers3cret!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  monarc_data:
